-- By Any Means Necessary IV
delete from quest_template where entry = 40400;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (40399,40400,2,361,53,47,0,0,'By Any Means Necessary IV','You have done me a great service in gathering this artifact from amongst those demonic worshippers. It will be better served in my hands, rather then to serve evil.\n\nI may have used you for my own good, but I am not a traitor, and I will make it worth your while now that you have achieved what I desired. I will forge for you a Glaive in my namesake, one that can slay all manner of the Burning Legion. But, I will not depart with such a weapon so easily, I require one last exchange.\n\nDeep within the Sunken Temple are the guardians of the Green Dragonflight, corrupted, and twisted from their long slumber in the Emerald Dream. One of their defenders, Hazzas is one I knew long ago, he is a powerful being, and should not be tormented any longer.\n\nBring me his heart, and free him from torment, only then will you earn your reward.','Travel to the Sunken Temple, and find the Dragonkin Hazzas, slay him, and return the Heart of Hazzas to Niremius Darkwind.','There is taint all across Azeroth, can you feel the world itself calling for aid?','The Heart of Hazzas, you are resourceful $R , much more then I would have ever anticipated, now then, to forge your weapon,as I had promised.',60535,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6350,69,200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'');

replace into creature_questrelation (id, quest) values (60710, 40400);
replace into creature_involvedrelation (id, quest) values (60710, 40400);

update quest_template set type = 81 where entry = 40400;

replace into item_template (entry, display_id, name, class, quality, flags, buy_count, allowable_class, allowable_race, item_level, stackable, spellcooldown_1, spellcategorycooldown_1, spellcooldown_2, spellcategorycooldown_2, bonding, description, page_text) values
(60535,1290,'Heart of Hazzas',12,1,2048,1,-1,-1,1,1,-1,-1,-1,-1,4,'',0);

REPLACE INTO creature_loot_template VALUES
(5722, 60535, -100, 0, 1, 1, 0);