REPLACE INTO gameobject_template VALUES
(2010887, 9, 559, 'History of Darrowgaze', 0, 0, 1, 50528, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

REPLACE INTO `page_text` (`entry`, `text`, `next_page`) VALUES
(50528, 'Darrowgaze Tower\n\nA longstanding watchtower that was built during the Arathorian Empire during the unification of the human tribes before the Troll Wars. It served as a military sentry tower and has been standing everstill, even serving its purpose under the flag of Lordaeron but after the nobles who were in it\'s stead it fell on hard times due to a trade recession it fell into decline up until the second war where it was raided by the Horde and later used as an ambush location.', 50529),
(50529, 'During the time Alexandros Mograine led the Scarlet Crusade, it became the forward outpost for the Scarlet\'s and gained the new name of Ember Point, but after Alexandros was betrayed, the Argent Crusade took it over and renamed it Ardent Watch as a forward outpost to combat the Scourge. After the disbandment of the Argent Vanguard, It has now been refortified under the banner of The Crusade, another holy order.', 50530),
(50530, 'The Argent Vanguard\n\nA foreign operations battalion of the Argent Crusade under the leadership of Aurelian the Paladin who wielded Sulfuras during his operation, accepting Horde and Alliance alike so long as they slay the Scourge and hold to a non-aggression pact while in their order, they completed missions against the Scourge all throughout Azeroth including assaults against many Scourge fortifications and controlled territories such as the great Necropolis of Naxxramas.', 50531),
(50531, 'Unfortunately the Argent Vanguard was disbanded but the retired Paladin Aurelian has overseen the transfer of Ardent Watch to another holy order named The Crusade to protect and utilize Darrowgaze in the Vanguard\'s absence.', 50532),
(50532, 'The Crusade\n\nAn order of priests, clerics, friars and paladins alike who operated as a holy military order during the second war under the Nations of the Alliance. Disbanded in the separation of the first order of the Silver Hand with the creation of the Argent Crusade and the fanatical offshoot of the Scarlet Crusade.', 50533),
(50533, 'The Crusade returns into fruition without moniker such as \"Scarlet\" or \"Argent\" as we are the original order that came before, standing along side the Silver Hand. The Crusade has been reinstated within the Alliance once again in reaction to the arising threat of new heretics from the Horde and ancient foes of undeath and demonic nature persisting across Azeroth.', 0);