-- https://github.com/slowtorta/turtlewow-bug-tracker/issues/1494
UPDATE quest_template SET Title = 'Imperial Plate Belt', Objectives = 'For the belt plans, I\'ll be needin\' 20 thorium bars.', RequestItemsText = 'For the belt plans, I\'ll be needin\' 20 thorium bars.', ReqItemCount1 = 20 WHERE entry = 7653;
UPDATE quest_template SET Title = 'Imperial Plate Boots', Objectives = 'For the boot plans, I\'ll be needin\' 40 thorium bars. Yep, 40. Are you gonna cry? Would you like a hanky?', RequestItemsText = 'For the boot plans, I\'ll be needin\' 40 thorium bars. Yep, 40. Are you gonna cry? Would you like a hanky?$B$B<Derotain laughs.>', ReqItemCount1 = 40 WHERE entry = 7654;
UPDATE quest_template SET Title = 'Imperial Plate Bracer', Objectives = 'For the bracer plans, I\'ll be needin\' 20 thorium bars.', RequestItemsText = 'For the bracer plans, I\'ll be needin\' 20 thorium bars.$B$BAre you alright, sonny? Yer getting\' all red.', ReqItemCount1 = 20 WHERE entry = 7655;
UPDATE quest_template SET Title = 'Imperial Plate Chest', Objectives = 'For the chest piece plans, I\'ll be needin\' 60 thorium bars.\n\nOh boy, there you go again. Are you gonna be runnin\' to yer blue Gods, askin\' why they have forsaken you?!?\n\nToughen up, Nancy! Nobody ever said life\'s fair.', RequestItemsText = 'For the chest piece plans, I\'ll be needin\' 60 thorium bars.$B$B$BOh boy, there you go again. Are you gonna be runnin\' to yer blue Gods, askin\' why they have forsaken you?!? Toughen up, Nancy! Nobody ever said life\'s fair.', ReqItemCount1 = 60 WHERE entry = 7656;
UPDATE quest_template SET Title = 'Imperial Plate Helm', Objectives = 'Just hand over 50 thorium bars and the helm plans are yers.', RequestItemsText = 'Just hand over 50 thorium bars and the helm plans are yers.', ReqItemCount1 = 50 WHERE entry = 7657;
UPDATE quest_template SET Title = 'Imperial Plate Leggings', Objectives = 'Just hand over 60 thorium bars and the leg plans are yers.\n\nI know, I\'m driving you into bankruptcy! I\'ve heard it all before so you can save your sob story, weakling.', RequestItemsText = 'Just hand over 60 thorium bars and the leg plans are yers.$B$BI know, I\'m driving you into bankruptcy! I\'ve heard it all before so you can save your sob story, weakling.', ReqItemCount1 = 60 WHERE entry = 7658;
UPDATE quest_template SET Title = 'Imperial Plate Shoulders', Objectives = 'For the shoulder plans, I\'ll be needin\' 20 thorium bars.', RequestItemsText = 'For the shoulder plans, I\'ll be needin\' 20 thorium bars.', ReqItemCount1 = 20 WHERE entry = 7659;
UPDATE quest_template SET Title = 'Imperial Plate Gauntlets', Objectives = 'For the gauntlets plans, I\'ll be needin\' 20 thorium bars.', RequestItemsText = 'For the gauntlets plans, I\'ll be needin\' 20 thorium bars.$B$BAre you alright, sonny? Yer getting\' all red.', ReqItemCount1 = 20 WHERE entry = 55300;
