replace into migrations values (20191005154020);

replace into quest_template (entry, method, minlevel, questlevel, type, zoneorsort, prevquestid, nextquestid, nextquestinchain, title,
                             details, objectives, offerrewardtext, requestitemstext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, rewitemid1, rewitemcount1,
                             rewrepfaction1, rewrepvalue1) values
(60000, 2, 1, 60, 0, 284, 0, 60001, 60001, 'Party Means Presents', 'Oh, I know of a good present I\'d love to have. It\'s not near, not easy to get, not even something you could buy… Something untangible yet so much valuable.$B$BI haven\'t seen my li\'l fella Nozdormu so long and I\'m kinda miss him. What do you mean he\'s not available? Alrighty. What about Anachronos then? He\'s a bit stingy but he\'ll do as well.$B$BI\'d like to see him present. I mean come to party. Yeah, like in person. He\'s my li\'l sweet peach after all. Bring me to see him, $N. That''d be a great present for me. Sure thing for you too.', 'Make sure Speedy can see Anachronos today.', 'Yaaaaay! Best present and best party!', 'Are we already there?', 0, 0, 0, 0, 0, 0, 0, 0, 910, 500),
(60001, 2, 1, 60, 0, 284, 60000, 60002, 60002, 'Spirits of the Party!', 'There\'s something we truly miss now, my friend. Not dwarves. I mean, yes, we miss\'em all the time, since they are mostly busy with brewing something up. Oh, that reminds me, we need some liquor, spirits, wine and beverages of all sorts!$B$BI heard there are so many across the whole Azeroth. Could you please bring\'em in? No doubts you\'ll have your share as well.', 'Bring 20 Skin of Dwarven Stout to Speedy.', 'I heard they call it booze. Booze! Can you believe it? Hehehe!', 'Bring me the booze!', 2596, 20, 0, 0, 0, 0, 2594, 20, 0, 0),
(60002, 2, 1, 60, 0, 284, 60001, 60003, 60003, 'Cake is Real!', 'Yes! I\'m having a Birthday party! Can\'t you see the cake? Oh, true. There\'s none. Was it Chromie again? Hmm…$B$BBut you\'re absolutely right, it\'s not really a party with no cake on the platter. Could you, perhaps help me out with the ingredients?', 'Bring 5 Ice Cold Milk, 3 Small Egg and 10 Soothing Spices to Speedy', 'Thanks! I can now start preparing the cake.', 'Come oooon, I want to start cooking.', 1179, 3, 6889, 3, 3713, 10, 21215, 20, 0, 0),
(60003, 0, 1, 60, 0, 284, 60002, 0, 0, 'Thanks a lot', '', '', 'This is the best party I have ever had.$B$BThanks a lot for taking care of me for this entire year.', '', 0, 0, 0, 0, 0, 0, 51021, 1, 0, 0);

update item_template set script_name = '', spellid_1 = 19222, spellcharges_1 = -1 where entry = 51020;
