replace into migrations values (20200304232201);

update item_template set script_name = 'item_holystrike_libram' where entry = 51270;
update item_template set script_name = 'item_holystrike_libram' where entry = 51271;
update item_template set script_name = 'item_holystrike_libram' where entry = 51272;
update item_template set script_name = 'item_holystrike_libram' where entry = 51273;
update item_template set script_name = 'item_holystrike_libram' where entry = 51274;
update item_template set script_name = 'item_holystrike_libram' where entry = 51275;
update item_template set script_name = 'item_holystrike_libram' where entry = 51276;
update item_template set script_name = 'item_winter_tree' where entry = 51250;
update item_template set script_name = 'item_player_zeaus' where entry = 51066;
update item_template set script_name = 'item_player_zeaus' where entry = 51067;
update item_template set script_name = 'item_player_engie' where entry = 51055;
update item_template set script_name = 'item_player_engie' where entry = 51065;
update item_template set script_name = 'item_player_engie' where entry = 51209;
update item_template set script_name = 'item_player_engie' where entry = 51246;
update item_template set script_name = 'item_player_engie' where entry = 51247;
update item_template set script_name = 'item_player_engie' where entry = 51253;
update item_template set script_name = 'item_transmog' where entry = 51217;
update item_template set script_name = 'item_schnapps' where entry = 51020;
update item_template set script_name = 'item_radio' where entry = 51021;
update item_template set script_name = 'item_exhaustion_glyph' where entry = 50521;
update item_template set script_name = 'item_morph_succubus' where entry = 51208;
update item_template set script_name = 'item_morph_serpentlord' where entry = 51207;
update item_template set script_name = 'item_morph_banshee' where entry = 51206;
update item_template set script_name = 'item_morph_ghost' where entry = 51205;
update item_template set script_name = 'item_morph_dryad' where entry = 51204;
update item_template set script_name = 'item_morph_dryad' where entry = 50408;
update item_template set script_name = 'item_morph_highelf' where entry = 50017;
update item_template set script_name = 'item_morph_highelf' where entry = 51203;
update item_template set script_name = 'item_morph_bloodelf' where entry = 51202;
update item_template set script_name = 'item_morph_worgen' where entry = 51201;
update item_template set script_name = 'item_morph_goblin' where entry = 51200;
update item_template set script_name = 'item_bg_tabard' where entry in (19031, 19032, 19505, 19506, 20131, 20132);
update item_template set script_name = 'item_survival_boat' where entry = 50235;
update item_template set script_name = 'item_survival_tent' where entry = 50234;
update item_template set script_name = 'item_survival_kit' where entry = 50230;	
update item_template set script_name = 'item_skin_change' where entry = 50105;
update item_template set script_name = 'item_skin_change' where entry = 50106;
update item_template set script_name = 'item_skin_change' where entry = 50204;
update item_template set script_name = 'item_skin_change' where entry = 50205;
update item_template set script_name = 'item_skin_change' where entry = 50206;
update item_template set script_name = 'item_skin_change' where entry = 50207;
update item_template set script_name = 'item_skin_change' where entry = 50208;
update item_template set script_name = 'item_skin_change' where entry = 50209;
update item_template set script_name = 'item_skin_change' where entry = 50210;
update item_template set script_name = 'item_skin_change' where entry = 50211;
update item_template set script_name = 'item_skin_change' where entry = 50212;
update item_template set script_name = 'item_skin_change' where entry = 51010;
update item_template set script_name = 'item_skin_change' where entry = 51011;
update item_template set script_name = 'item_hairdye' where entry between 50107 and 50171;
update item_template set script_name = 'item_sword_of_truth' where entry = 50094;
update item_template set script_name = 'item_portable_mailbox' where entry = 50011;
update item_template set script_name = 'item_city_portal' where entry = 50056;
update item_template set script_name = 'item_city_portal' where entry = 50057;
update item_template set script_name = 'item_summer_vestment' where entry = 50046;
update item_template set script_name = 'item_scaler' where entry = 50020;
update item_template set script_name = 'item_scaler' where entry = 50021;
update item_template set script_name = 'item_roleplay_hub' where entry = 50016;
update item_template set script_name = 'item_character_rename' where entry = 50000;

delete from item_template where entry between 51290 and 51294;
delete from item_template where entry between 51230 and 51238;
delete from item_template where entry = 51215;
delete from item_template where entry = 51202;
delete from item_template where entry = 51204;