

-- Change Goblins starting point:

UPDATE `playercreateinfo` SET `position_x` = -233, `position_y` =  -7177, `position_z` = 16.52, `orientation` = 1.76 WHERE `race` = 9;

-- Generated by "GenerateCameraMesh" program. Giperion 2020 - 2023 for Turtle project

DELETE FROM cinematic_waypoints WHERE cinematic = 164;

INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '0', '189', '-8346', '32', 'FlyByGoblin.m2_0');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '6000', '120', '-8101', '32', 'FlyByGoblin.m2_1');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '12000', '-17', '-8007', '69', 'FlyByGoblin.m2_2');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '18000', '-168', '-7824', '46', 'FlyByGoblin.m2_3');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '23000', '-207', '-7768', '46', 'FlyByGoblin.m2_4');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '30000', '-269', '-7605', '116', 'FlyByGoblin.m2_5');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '41000', '-309', '-7421', '101', 'FlyByGoblin.m2_6');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '45000', '-321', '-7372', '74', 'FlyByGoblin.m2_7');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '46000', '-314', '-7372', '69', 'FlyByGoblin.m2_8');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '49000', '-279', '-7369', '60', 'FlyByGoblin.m2_9');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '50000', '-277', '-7361', '58', 'FlyByGoblin.m2_10');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '55000', '-244', '-7314', '40', 'FlyByGoblin.m2_11');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '59000', '-238', '-7233', '32', 'FlyByGoblin.m2_12');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '61000', '-236', '-7202', '26', 'FlyByGoblin.m2_13');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '62000', '-236', '-7202', '25.9', 'FlyByGoblin.m2_14');

