-- Shard Harmonization
delete from quest_template where entry = 40813;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,40813,2,616,60,55,0,1,'Kaldorei Weaponry','We must all do our part here in Hyjal, and my part is to harmonize Small Dream Shards into Bright Dream Shards. The harmonization process makes the shards much more potent in regards to their magical properties. If you have any work that you need me to do, bring me three Small Dream Shards, they can be found around Hyjal, or no doubt earned by those in town for tasks in maintaining Nordrassil.','Collect 3 Small Dream Shards for Lantho Talonmoon at Nordanaar in Hyjal.','So you\'ve returned, do you have those shards ready for me?','Excellent work, the harmonization process does not take me long, especially with all this practice, if you find any more, come and let me know.',61198,3,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,450,0,0,0,0,0,0,0,0,0,0,0, 61199,1,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (61325, 40813);
replace into creature_involvedrelation	(id, quest) values (61325, 40813);

-- quest Kaldorei Weaponry (entry 40813) rename to Shard Harmonization.
update quest_template set title = 'Shard Harmonization' where entry = 40813;
