
-- Generated by "GenerateCameraMesh" program. Giperion 2020 - 2023 for Turtle project

DELETE FROM cinematic_waypoints WHERE cinematic = 162;

INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '0', '4926', '-3056', '54', 'FlyByElf.m2_0');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '4000', '4832', '-3021', '53', 'FlyByElf.m2_1');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '12500', '4629', '-2935', '53', 'FlyByElf.m2_2');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '16000', '4511', '-2904', '24', 'FlyByElf.m2_3');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '25000', '4326', '-2847', '15', 'FlyByElf.m2_4');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '33000', '4146', '-2752', '54', 'FlyByElf.m2_5');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '37000', '4018', '-2741', '68', 'FlyByElf.m2_6');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '39000', '3986', '-2705', '61', 'FlyByElf.m2_7');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '49000', '3878', '-2551', '47', 'FlyByElf.m2_8');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '51000', '3840', '-2545', '51', 'FlyByElf.m2_9');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '63000', '3619', '-2472', '99', 'FlyByElf.m2_10');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '71000', '3405', '-2457', '112', 'FlyByElf.m2_11');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '75000', '3338', '-2450', '143', 'FlyByElf.m2_12');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '87000', '3231', '-2488', '128', 'FlyByElf.m2_13');



