
-- Generated by "GenerateCameraMesh" program. Giperion 2020 - 2023 for Turtle project
-- goblin cinematic
DELETE FROM cinematic_waypoints WHERE cinematic = 164;

INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '0', '185', '-8336', '32', 'FlyByGoblin.m2_0');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '6000', '120', '-8101', '32', 'FlyByGoblin.m2_1');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '12000', '-17', '-8007', '69', 'FlyByGoblin.m2_2');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '19000', '-168', '-7824', '46', 'FlyByGoblin.m2_3');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '23000', '-207', '-7768', '47', 'FlyByGoblin.m2_4');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '32000', '-269', '-7605', '116', 'FlyByGoblin.m2_5');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '41000', '-309', '-7421', '101', 'FlyByGoblin.m2_6');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '45000', '-321', '-7372', '74', 'FlyByGoblin.m2_7');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '46000', '-314', '-7372', '69', 'FlyByGoblin.m2_8');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '49000', '-279', '-7369', '60', 'FlyByGoblin.m2_9');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '50000', '-277', '-7361', '58', 'FlyByGoblin.m2_10');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '54000', '-244', '-7314', '40', 'FlyByGoblin.m2_11');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '59000', '-238', '-7233', '32', 'FlyByGoblin.m2_12');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '62000', '-236', '-7202', '25.9', 'FlyByGoblin.m2_13');

-- elf
DELETE FROM cinematic_waypoints WHERE cinematic = 162;

INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '0', '4926', '-3056', '54', 'FlyByElf.m2_0');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '4000', '4832', '-3021', '53', 'FlyByElf.m2_1');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '12500', '4629', '-2935', '53', 'FlyByElf.m2_2');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '16000', '4511', '-2904', '24', 'FlyByElf.m2_3');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '25000', '4326', '-2847', '15', 'FlyByElf.m2_4');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '33000', '4146', '-2752', '54', 'FlyByElf.m2_5');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '39000', '3962', '-2738', '63', 'FlyByElf.m2_6');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '49000', '3854', '-2588', '52', 'FlyByElf.m2_7');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '51500', '3840', '-2545', '51', 'FlyByElf.m2_8');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '63000', '3619', '-2442', '96', 'FlyByElf.m2_9');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '71000', '3405', '-2457', '112', 'FlyByElf.m2_10');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '75000', '3338', '-2450', '143', 'FlyByElf.m2_11');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('162', '87000', '3231', '-2488', '128', 'FlyByElf.m2_12');


