UPDATE quest_template SET
Details = 'The Living? Here? I never thought I would see the day.$B$BMy cursed spirit is forever bound here, unable to find the sweet release of true death. The memories of my past still haunt me, a never-ending reminder of the consequences of my actions.$B$BYet, here you stand, wandering through these halls, oblivious to the horrors that await you. Stay for a while and listen to my story, if it is the mysteries of Karazhan you seek to unravel. But be warned, for there are darker secrets buried within these walls that even I am not privy to.$B$BIf you are determined enough to delve into the enigmas of Medivh''s tower, perhaps the true purpose of this accursed place will reveal itself. Or perhaps you will simply become lost to the madness that has ensnared so many others before you. A tormented spectre of the past, forever trapped within these walls, just like me...',
OfferRewardText = 'After years spent wandering these halls as a phantom, I have come to accept the weight of my actions and the consequences that have befallen me. I do not seek absolution or forgiveness from you, for that is not within your power to grant.$B$BInstead, I ask that you consider that which I have revealed to you. Reflect upon my story and the lessons that can be learned from it. Perhaps you too have had a hunger for power or knowledge that has clouded your judgment in the past. Or maybe you have made mistakes that you regret and wish to make amends for.$B$BAs for the next course of action, that too is for you to decide. Will you seek out the key to the Upper Chambers of Karazhan and uncover its secrets? Or will you leave this accursed place behind and seek your fortunes elsewhere? Only you can decide the path that lies before you.'
WHERE entry = 40817;

UPDATE quest_template SET
OfferRewardText = 'In life, Medivh was known to be an extremely cautious and paranoid individual, and he took great measures to ensure that only he and his most trusted allies could access the key to his chambers. Even I, as his friend, was forbidden from doing so.$B$BBut there may be a glimmer of hope yet - if we can locate Echoes of Medivh''s presence, they may be powerful enough to fuel the key. Those with great magical abilities often leave traces of their presence in the fabric of the leylines, causing disruptions that can still be felt long after they are gone.$B$BThese echoes tend to linger in places of great significance to the person''s story, so we must scour the land for any clues or signs that may lead us to the echoes of Medivh. It won''t be an easy task, but it is our only hope of gaining access to Karazhan''s chambers and preventing the dark forces that threaten to consume us all.'
WHERE entry = 40825;

UPDATE quest_template SET
Details = 'If you desire to learn more, I will require some favors before I can impart what knowledge I can glean from this parchment. When I first arrived in Karazhan some time ago, I wore an engraved bracelet made of the finest gold. It was a symbol of my status, and has subsequently gone missing ever since I have been roaming and haunting these halls.$B$BI am certain I left my bracelet somewhere within these lower halls. Recover it for me, and I will be quite thankful.'
WHERE entry = 40999;
