-- Pool of pools for Thorium Veins in Eastern Kingdoms.
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`, `flags`, `instance`) VALUES (5616, 100, 'Thorium Veins in Eastern Kingdoms', 0, 0);
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5000, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5002, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5003, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5004, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5017, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5021, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5022, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5024, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5025, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5026, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5027, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5030, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5031, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5032, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5035, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5036, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5041, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5044, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5045, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5046, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5048, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5051, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5053, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5058, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5060, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5064, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5067, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5071, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5073, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5075, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5077, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5085, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5086, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5088, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5089, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5091, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5096, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5097, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5100, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5101, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5102, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5103, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5106, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5107, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5111, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5113, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5115, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5120, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5121, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5123, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5124, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5126, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5128, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5130, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5132, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5135, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5136, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5138, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5139, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5142, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5144, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5149, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5151, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5153, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5157, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5163, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5164, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5165, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5166, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5171, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5173, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5175, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5186, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5188, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5192, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5193, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5196, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5197, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5199, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5200, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5204, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5209, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5211, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5214, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5216, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5219, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5221, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5225, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5226, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5227, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5228, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5229, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5230, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5233, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5235, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5237, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5243, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5244, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5251, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5279, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5278, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5276, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5274, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5273, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5272, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5271, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5270, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5252, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5253, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5264, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5265, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5266, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5267, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5268, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5269, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5275, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5280, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5282, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5263, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5283, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5284, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5285, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5286, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5287, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5288, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5289, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5290, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5291, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5292, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5293, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5294, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5295, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5296, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5297, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5298, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5402, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5403, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5405, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5407, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5410, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5411, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5415, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5416, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5419, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5420, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5422, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5424, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5430, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5431, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5433, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5436, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5437, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5438, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5439, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5442, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5443, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5444, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5445, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5446, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5448, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5453, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5454, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5455, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5461, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5462, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5463, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5471, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5472, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5475, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5478, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5479, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5480, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5483, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5484, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5485, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5488, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5492, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5493, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5494, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5496, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5497, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5498, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5499, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5500, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5504, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5505, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5506, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5507, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5509, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5510, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5516, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5518, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5520, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5522, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5524, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5527, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5528, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5529, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5530, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5531, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5532, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5533, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5534, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5535, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5536, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5537, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5575, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5576, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5577, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5579, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5590, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5591, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5592, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5593, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5594, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5595, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5596, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5597, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5598, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5599, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5600, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5603, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5605, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5364, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5367, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5366, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5365, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5359, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5369, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5368, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5370, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5371, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5372, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5373, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5374, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5375, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5376, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5377, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5378, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5379, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5380, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5381, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5382, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5383, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5384, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5363, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5362, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5361, 5616, 0, 'Thorium Vein in Eastern Kingdoms');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5360, 5616, 0, 'Thorium Vein in Eastern Kingdoms');

-- Pool of pools for Thorium Veins in Kalimdor.
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`, `flags`, `instance`) VALUES (5617, 150, 'Thorium Veins in Kalimdor', 0, 0);
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5001, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5005, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5006, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5007, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5008, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5009, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5010, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5011, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5012, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5013, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5014, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5015, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5016, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5018, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5019, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5020, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5023, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5028, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5029, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5033, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5034, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5037, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5038, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5039, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5040, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5042, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5043, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5047, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5049, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5050, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5052, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5054, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5055, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5056, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5057, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5059, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5061, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5062, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5063, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5065, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5066, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5068, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5069, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5070, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5072, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5074, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5076, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5078, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5079, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5080, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5081, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5082, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5083, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5084, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5087, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5090, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5092, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5093, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5094, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5095, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5098, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5099, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5104, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5105, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5108, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5109, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5110, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5112, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5114, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5116, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5117, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5118, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5119, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5122, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5125, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5127, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5129, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5131, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5133, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5134, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5137, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5140, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5141, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5143, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5145, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5146, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5147, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5148, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5150, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5152, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5154, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5155, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5156, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5158, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5159, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5160, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5161, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5162, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5167, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5168, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5169, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5170, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5172, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5174, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5176, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5177, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5178, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5179, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5180, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5181, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5182, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5183, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5184, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5185, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5187, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5189, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5190, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5191, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5194, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5195, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5198, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5201, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5202, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5203, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5205, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5206, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5207, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5208, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5210, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5212, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5213, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5215, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5217, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5218, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5220, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5222, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5223, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5224, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5231, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5232, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5234, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5236, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5238, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5239, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5240, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5241, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5242, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5245, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5246, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5247, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5248, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5249, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5250, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5262, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5261, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5260, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5259, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5258, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5257, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5256, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5255, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5254, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5277, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5281, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5299, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5300, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5301, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5302, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5303, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5304, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5305, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5306, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5307, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5308, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5309, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5310, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5311, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5312, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5313, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5314, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5315, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5316, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5317, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5400, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5401, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5404, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5406, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5408, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5409, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5412, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5413, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5414, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5417, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5418, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5421, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5423, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5425, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5426, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5427, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5428, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5429, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5432, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5434, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5435, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5440, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5441, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5447, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5449, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5450, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5451, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5452, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5456, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5457, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5458, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5459, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5460, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5464, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5465, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5466, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5467, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5468, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5469, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5470, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5473, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5474, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5476, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5477, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5481, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5482, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5486, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5487, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5489, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5490, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5491, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5495, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5501, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5502, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5503, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5508, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5511, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5512, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5513, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5514, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5515, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5517, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5519, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5521, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5523, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5525, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5526, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5538, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5539, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5540, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5541, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5542, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5543, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5544, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5545, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5546, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5547, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5548, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5549, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5550, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5551, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5552, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5553, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5554, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5555, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5556, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5557, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5558, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5559, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5560, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5561, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5562, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5563, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5564, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5565, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5566, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5567, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5568, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5569, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5570, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5571, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5572, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5573, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5574, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5578, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5580, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5581, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5582, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5583, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5584, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5585, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5586, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5587, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5588, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5589, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5601, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5602, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5604, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5606, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5607, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5608, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5609, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5610, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5611, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5612, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5613, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5614, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5615, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5397, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5396, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5395, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5394, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5393, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5392, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5391, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5390, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5389, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5388, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5387, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5386, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5385, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5398, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5399, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5358, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5357, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5356, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5355, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5354, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5353, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5352, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5351, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5350, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5349, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5348, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5347, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5346, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5345, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5344, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5343, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5342, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5341, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5340, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5339, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5338, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5337, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5336, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5335, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5334, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5333, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5332, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5331, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5330, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5329, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5328, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5327, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5326, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5325, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5324, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5323, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5322, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5321, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5320, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5319, 5617, 0, 'Thorium Vein in Kalimdor');
INSERT INTO `pool_pool` (`pool_id`, `mother_pool`, `chance`, `description`) VALUES (5318, 5617, 0, 'Thorium Vein in Kalimdor');



