replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 439, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 440, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 441, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 835, 0, 'Tidal Charm');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2024, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2330, 0, 'Minor Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2331, 0, 'Minor Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2332, 0, 'Minor Rejuvenation Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2335, 0, 'Swiftness Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2337, 0, 'Lesser Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2339, 0, 'Minor Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2340, 0, 'Minor Rejuvenation Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 2341, 0, 'Lesser Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3173, 0, 'Lesser Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3175, 0, 'Limited Invulnerability Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3181, 0, 'Lesser Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3447, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3448, 0, 'Lesser Invisibility Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3452, 0, 'Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3458, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3459, 0, 'Lesser Invisibility Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3461, 0, 'Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3919, 0, 'Rough Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3923, 0, 'Rough Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3931, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3937, 0, 'Large Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3941, 0, 'Small Bronze Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3944, 0, 'Flame Deflector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3946, 0, 'Heavy Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3950, 0, 'Big Bronze Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3952, 0, 'Minor Recombobulator');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3955, 0, 'Explosive Sheep');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3957, 0, 'Ice Deflector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3959, 0, 'Discombobulator Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3960, 0, 'Portable Bronze Mortar');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3962, 0, 'Iron Grenade');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3963, 0, 'Compact Harvest Reaper Kit');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3967, 0, 'Big Iron Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3968, 0, 'Goblin Land Mine');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3969, 0, 'Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3971, 0, 'Gnomish Cloaking Device');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3981, 0, 'Rough Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3985, 0, 'Rough Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3994, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 3999, 0, 'Large Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4003, 0, 'Small Bronze Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4007, 0, 'Heavy Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4010, 0, 'Big Bronze Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4011, 0, 'Minor Recombobulator');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4013, 0, 'Explosive Sheep');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4015, 0, 'Ice Deflector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4018, 0, 'Iron Grenade');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4019, 0, 'Compact Harvest Reaper Kit');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4023, 0, 'Big Iron Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4024, 0, 'Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4025, 0, 'Gnomish Cloaking Device');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4042, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4050, 0, 'Explosive Sheep');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4054, 0, 'Rough Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4061, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4062, 0, 'Heavy Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4064, 0, 'Rough Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4065, 0, 'Large Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4066, 0, 'Small Bronze Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4067, 0, 'Big Bronze Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4068, 0, 'Iron Grenade');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4069, 0, 'Big Iron Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4073, 0, 'Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4074, 0, 'Explosive Sheep');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4100, 0, 'Goblin Land Mine');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4508, 0, 'Discolored Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 4942, 0, 'Lesser Stoneshield Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 5134, 0, 'Flash Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 6617, 0, 'Rage Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 6618, 0, 'Great Rage Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 6624, 0, 'Free Action Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7181, 0, 'Greater Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7182, 0, 'Greater Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7255, 0, 'Holy Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7256, 0, 'Shadow Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7257, 0, 'Fire Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7258, 0, 'Frost Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 7259, 0, 'Nature Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8079, 0, 'Rough Copper Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8209, 0, 'Explosive Sheep');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8243, 0, 'Flash Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8331, 0, 'Ez-Thro Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8333, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8339, 0, 'EZ-Thro Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8892, 0, 'Goblin Rocket Boots');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 8895, 0, 'Goblin Rocket Boots');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 9002, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 9003, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 9004, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 9009, 0, 'Coarse Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 9273, 0, 'Goblin Jumper Cables');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 10837, 0, 'Goblin Land Mine');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11387, 0, 'Wildvine Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11448, 0, 'Greater Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11452, 0, 'Restorative Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11453, 0, 'Magic Resistance Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11457, 0, 'Superior Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11458, 0, 'Wildvine Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11464, 0, 'Invisibility Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11488, 0, 'Greater Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11491, 0, 'Superior Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11522, 0, 'Restorative Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 11595, 0, 'Discombobulator Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12419, 0, 'Solid Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12421, 0, 'Mithril Frag Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12543, 0, 'Hi-Explosive Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12562, 0, 'The Big One');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12586, 0, 'Solid Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12603, 0, 'Mithril Frag Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12607, 0, 'Catseye Ultra Goggles');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12619, 0, 'Hi-Explosive Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12624, 0, 'Mithril Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12630, 0, 'Solid Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12638, 0, 'Mithril Frag Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12641, 0, 'Hi-Explosive Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12716, 0, 'Goblin Mortar');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12718, 0, 'Goblin Construction Helmet');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12749, 0, 'Mithril Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12754, 0, 'The Big One');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12755, 0, 'Goblin Bomb Dispenser');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12758, 0, 'Goblin Rocket Helmet');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12759, 0, 'Gnomish Death Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12760, 0, 'Goblin Sapper Charge');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12768, 0, 'Goblin Mortar');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12770, 0, 'Goblin Construction Helmet');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12771, 0, 'Goblin Sapper Charge');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12776, 0, 'Goblin Rocket Boots');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12777, 0, 'Goblin Bomb Dispenser');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12778, 0, 'The Big One');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12779, 0, 'Gnomish Death Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12780, 0, 'Goblin Rocket Helmet');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12899, 0, 'Gnomish Shrink Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12902, 0, 'Gnomish Net-o-Matic Projector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12903, 0, 'Gnomish Harm Prevention Belt');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12905, 0, 'Gnomish Rocket Boots');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12906, 0, 'Gnomish Battle Chicken');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12907, 0, 'Gnomish Mind Control Cap');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12908, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12911, 0, 'Gnomish Shrink Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12913, 0, 'Gnomish Net-o-Matic Projector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12914, 0, 'Gnomish Harm Prevention Belt');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12916, 0, 'Gnomish Rocket Boots');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12917, 0, 'Gnomish Battle Chicken');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12918, 0, 'Gnomish Mind Control Cap');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 12919, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13141, 0, 'Gnomish Rocket Boots');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13180, 0, 'Gnomish Mind Control Cap');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13181, 0, 'Gnomish Mind Control Cap');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13183, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13184, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13237, 0, 'Goblin Mortar');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13238, 0, 'Goblin Mortar');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13241, 0, 'Goblin Sapper Charge');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13278, 0, 'Gnomish Death Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13279, 0, 'Gnomish Death Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13280, 0, 'Gnomish Death Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13466, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13479, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13493, 0, 'Gnomish Death Ray');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13711, 0, 'Goblin Rocket Helmet');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 13821, 0, 'Goblin Rocket Helmet');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15229, 0, 'Crystal Restore');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15231, 0, 'Crystal Force');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15239, 0, 'Crystal Charge');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15279, 0, 'Crystal Spire');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15700, 0, 'Whipper Root Tuber');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15701, 0, 'Night Dragon\'s Breath');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15833, 0, 'Dreamless Sleep Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 15834, 0, 'Dreamless Sleep Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 16666, 0, 'Demonic Rune');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17527, 0, 'Mighty Rage Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17534, 0, 'Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17552, 0, 'Mighty Rage Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17553, 0, 'Superior Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17556, 0, 'Major Healing Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17570, 0, 'Greater Stoneshield Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17572, 0, 'Purification Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17574, 0, 'Greater Fire Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17575, 0, 'Greater Frost Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17576, 0, 'Greater Nature Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17577, 0, 'Greater Arcane Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17578, 0, 'Greater Shadow Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17579, 0, 'Greater Holy Protection Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 17580, 0, 'Major Mana Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19199, 0, 'Tea with Sugar');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19769, 0, 'Thorium Grenade');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19784, 0, 'Dark Iron Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19790, 0, 'Thorium Grenade');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19799, 0, 'Dark Iron Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19804, 0, 'Arcanite Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19821, 0, 'Arcane Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19830, 0, 'Arcanite Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 19831, 0, 'Arcane Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 21167, 0, 'Snowball');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 21343, 0, 'Snowball');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 21688, 0, 'Goblin Land Mine');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 21833, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 21910, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 22732, 0, 'Major Rejuvenation Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 22739, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 22741, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23000, 0, 'Ez-Thro Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23050, 0, 'Mithril Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23051, 0, 'Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23052, 0, 'Arcanite Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23063, 0, 'Dense Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23069, 0, 'EZ-Thro Dynamite II');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23070, 0, 'Dense Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23074, 0, 'Arcanite Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23075, 0, 'Mithril Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23076, 0, 'Mechanical Dragonling');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23077, 0, 'Gyrofreeze Ice Reflector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23078, 0, 'Goblin Jumper Cables XL');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23079, 0, 'Major Recombobulator');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23081, 0, 'Hyper-Radiant Flame Reflector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23082, 0, 'Ultra-Flash Shadow Reflector');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23095, 0, 'Dense Dynamite');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 23133, 0, 'Gnomish Battle Chicken');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 24366, 0, 'Greater Dreamless Sleep Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 24367, 0, 'Living Action Potion');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 25677, 0, 'Snowball');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 26740, 0, 'Gnomish Mind Control Cap');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 27603, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 27604, 0, 'Goblin Dragon Gun');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 27869, 0, 'Dark Rune');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 29419, 0, 'Flash Bomb');
replace into instance_buff_removal (map_id, spell_id, enabled, comment) values (26, 46452, 0, 'Snowball');


-- select entry from spell_template where name in ("Tea with Sugar","Living Action Potion","Free Action Potion","Limited Invulnerability Potion","Invisibility Potion","Lesser Invisibility Potion","Swiftness Potion","Mighty Rage Potion","Restorative Potion","Major Mana Potion","Major Healing Potion","Healing Potion","Greater Healing Potion","Greater Arcane Protection Potion","Greater Shadow Protection Potion","Superior Mana Potion","Superior Healing Potion","Lesser Healing Potion","Greater Stoneshield Potion","Mana Potion","Major Rejuvenation Potion","Greater Fire Protection Potion","Purification Potion","Magic Resistance Potion","Shadow Protection Potion","Greater Mana Potion","Minor Mana Potion","Greater Nature Protection Potion","Minor Healing Potion","Greater Frost Protection Potion","Combat Mana Potion","Nature Protection Potion","Dreamless Sleep Potion","Rage Potion","Great Rage Potion","Lesser Mana Potion","Combat Healing Potion","Greater Dreamless Sleep Potion","Fire Protection Potion","Minor Rejuvenation Potion","Greater Holy Protection Potion","Lesser Stoneshield Potion","Wildvine Potion","Holy Protection Potion","Minor Magic Protection Potion","Frost Protection Potion","Discolored Healing Potion","Gnomish Shrink Ray","Gnomish Net-o-Matic Projector","Catseye Ultra Goggles","Gnomish Harm Prevention Belt","Tidal Charm","Gnomish Rocket Boots","Gnomish Battle Chicken","Gnomish Mind Control Cap","Gnomish Death Ray","Goblin Construction Helmet","Goblin Mortar","Goblin Sapper Charge","Goblin Rocket Boots","Goblin Bomb Dispenser","The Big One","Goblin Dragon Gun","Goblin Rocket Helmet","Minor Recombobulator","Ice Deflector","Flame Deflector","Discombobulator Ray","Goblin Jumper Cables","Compact Harvest Reaper Kit","Snowball","Gnomish Cloaking Device","Mechanical Dragonling","Mithril Mechanical Dragonling","Gyrofreeze Ice Reflector","Major Recombobulator","Gnomish Alarm-O-Bot","Goblin Jumper Cables XL","Hyper-Radiant Flame Reflector","Arcanite Dragonling","Ultra-Flash Shadow Reflector","Rough Copper Bomb","Rough Dynamite","Coarse Dynamite","Ez-Thro Dynamite","Large Copper Bomb","Small Bronze Bomb","Heavy Dynamite","Big Bronze Bomb","Explosive Sheep","Portable Bronze Mortar","Solid Dynamite","Iron Grenade","Flash Bomb","Big Iron Bomb","Goblin Land Mine","Ez-Thro Dynamite II","Mithril Frag Bomb","Hi-Explosive Bomb","Dense Dynamite","Thorium Grenade","Dark Iron Bomb","Arcane Bomb","Whipper Root Tuber","Night Dragon's Breath","Crystal Restore","Crystal Spire","Crystal Force","Crystal Charge","Demonic Rune","Dark Rune");