-- Fox name for GO Tree of Lashes:
delete from gameobject_template where entry = 2010796;
REPLACE INTO gameobject_template VALUES (2010796, 9, 25251, 'Tree of Lashes', 0, 0, 1, 50526, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, '');
REPLACE INTO page_text VALUES (50526, 'The Tree of Lashes is covered in countless wounds of varied age. Some still drip with sap, while others are faint, ghostly scars. One name is torn into the tree\'s flesh, and bleeds still: "Ariele."', 0);

-- A Diplomatic Mission --
delete from quest_template where entry = 40371;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (80256,40371,2,2040,60,60,0,0,'A Diplomatic Mission','Greetings, $N. While others see our people as only refugees and survivors of a once-great nation, we must show the rest of the Alliance that the Quel\'dorei are here to stay. With Alah\'thalas prospering and our people slowly mobilizing into a formidable force, this is a perfect time for us to officially join the Alliance. Our magisters have prepared a missives that needs to be delivered directly to the leaders of the Alliance, and I think that the honor of delivering such an important message should be yours.','Seek audience with all four Alliance leaders and represent Alah\'thalas interests.','What is it, $R?','As expected... The Night Elves continue to hold their ancient grudge. Although this is not an ideal situation, we still got positive replies from the majority of the Alliance members. Now we can focus on earning their trust and forging new allies. I hope we can count on you again should such need arise, and $N, thank you for all you have done.',83016,1,83017,1,83018,1,83019,1,0,0,0,0,0,0,0,0,83015,4,0,0,269,350,0,0,0,0,0,0,0,0,0,65018,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,'');

replace into creature_questrelation (id, quest) values (80245, 40371);
replace into creature_involvedrelation (id, quest) values (80245, 40371);

