update item_template set sheath = 2 where entry = 80642;
update quest_template set requiredclasses = 0 where entry = 60134;
update quest_template set details = 'Hello, young ranger, you appear to be doing well!\n\nOur people struggles but we must endure, we must become more able than we were before.\n\nWe Rangers were trained to protect Quel’thalas and its forests, but now we have to operate in entirely new environments.\n\nI believe we should look to the techniques of our allies in order to improve what remains of the Ranger Corps.\n\nThere is a dwarf in Dun Morogh called Grif Wildheart, he is said to be able to bend beasts to his will, such a technique would be useful to you, see if you can learn it from him.' where entry = 80366;
update quest_template set details = 'So it\'s Mildred who\'s asking you to help? Of course, I\'ll help! I was always fond of the Stonefields.\n\nPumpkins, huh? Well, the only gnolls I know that camp not so far away from here are the Riverpaw Gnolls. They are the leftovers of a tribe led by a mighty gnoll known all over Elwynn – Fedfennel.\n\nRumor has it he\'s been eaten by his own rivals. I digress, however. The camp is most likely further up to the north from Stone Cairn Lake.\n\nI heard that even our brave guards dare not to go that far in the forest. Perhaps, while you\'re at the searching campaign for stolen pumpkins, you could help the Eastvale Logging Camp as well?\n\nThese gnolls won\'t be willing to part that easily with what they\'ve stolen, so I assume you\'ll have to claw it out of their dead cold paws.\n\nDo us all good and cull out s\'more of these bastards while you\'re there? One brigade less and we\'ll have a week of sound sleep by nights.', offerrewardtext = 'You did what? All by yourself?!\n\nWell, that\'s great news! Nt least the gnolls will no longer cause us trouble from now on!\n\nHow did you know? Terry told you?', objectives = 'Kill 10 Riverpaw Runts and 10 Riverpaw Outrunners.' where entry = 60042;
update item_template set display_id = 20728 where entry = 51794;
update gameobject_loot_template set  = 100 where entry = 938 and item = 737;
update item_template set sell_price = 0 where entry = 18662;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 50 where entry = 6642;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 6643;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 6644;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 150 where entry = 6645;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 6646;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 1000 where entry = 7604;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 250 where entry = 7652;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 7653;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 7654;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 150 where entry = 7655;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 7656;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 7657;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 200 where entry = 7658;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 150 where entry = 7659;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7701;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 250 where entry = 7704;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7722;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7723;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7724;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7727;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7728;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 100 where entry = 7729;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 25 where entry = 7736;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 25 where entry = 7737;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 25 where entry = 8241;
update quest_template set rewrepfaction1 = 59, rewrepvalue1 = 25 where entry = 8242;
update creature_loot_template set chanceorquestchance = 46 where `entry` = 10916 and item = 21383;
update creature_loot_template set chanceorquestchance = 40 where `entry` = 10738 and item = 21383;
update creature_loot_template set chanceorquestchance = 45 where `entry` = 7442 and item = 21383;
update creature_loot_template set chanceorquestchance = 42 where `entry` = 7441 and item = 21383;
update creature_loot_template set chanceorquestchance = 45 where `entry` = 7440 and item = 21383;
update creature_loot_template set chanceorquestchance = 40 where `entry` = 7439 and item = 21383;
update creature_loot_template set chanceorquestchance = 36 where `entry` = 7438 and item = 21383;
