CREATE TABLE IF NOT EXISTS `hardcore_deaths` (
	`lowGuid` INT(10) UNSIGNED NOT NULL,
	`race` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`class` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
	`level` INT(10) UNSIGNED NOT NULL,
	`attackerEntry` INT(10) UNSIGNED NOT NULL,
	`position_x` FLOAT(12) NOT NULL DEFAULT '0',
	`position_y` FLOAT(12) NOT NULL DEFAULT '0',
	`position_z` FLOAT(12) NOT NULL DEFAULT '0',
	`mapId` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`lowGuid`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
