delete from quest_template where entry = 40120;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4) values (0,40120,2,331,13,20,0,0,'Aggresive Wildlife','The encroaching wildlife has become a problem for both myself and my wife. In the past we lived at peace with the animals of the forest, though it now seems we must always be wary of our moves and watch the forests for the eyes of stalking predators.\n\nThe Ghostpaw have been especially troublesome and have for days now stalked our house for signs of weakness. I have given them none but I fear that something may be driving the wildlife to act in a much more aggresive manner.\n\nRegardless, gather me five of their pelts, thin the numbers so that they are not so brazen in their attacks, you can find Ghostpaw Wolves all around the forest.','Slay Ghostpaw Wolves and bring their pelts to Ardaen.','Have you made the forests a safer place, friend?','I must thank you dearly for the work you have put in, you have made it easier for us out here, but I feel one more thing must be done.',60110,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,1350,69,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);

replace into creature_questrelation (id, quest) values (91288, 40120);
replace into creature_involvedrelation (id, quest) values (91288, 40120);

delete from item_template where entry = 60110;
replace into item_template (entry, display_id, name, class, quality, flags, buy_count, allowable_class, allowable_race, item_level, stackable, spellcooldown_1, spellcategorycooldown_1, spellcooldown_2, spellcategorycooldown_2, bonding) values (60110,1421,'Ghostpaw Pelt',12,1,2048,1,-1,-1,1,5,-1,-1,-1,-1,4);

replace into creature_loot_template (entry, item, chanceorquestchance, mincountorref, maxcount, condition_id, patch_max) values (3823,60110,-35,1,1,0,10);

