CREATE TABLE `arena_stats_single` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`arena_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`team_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`item_level` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`class` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`race` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`won` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`duration` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`date` DATETIME NOT NULL DEFAULT current_timestamp(),
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
